import React, {useState} from 'react';
export default function App(){
  const [token,setToken]=useState(localStorage.getItem('token'));
  return (<div style={{padding:20,fontFamily:'Arial'}}>{!token ? <Auth onSuccess={(t)=>{localStorage.setItem('token',t); setToken(t);}} /> : <Calculator token={token} />}</div>);
}
function Auth({onSuccess}){ const [mode,setMode]=useState('login'); return (<div style={{display:'flex',gap:20}}><div style={{width:360}}>{mode==='login'? <Login onSuccess={onSuccess}/> : <Register onSuccess={onSuccess}/>}</div><div><button onClick={()=>setMode(mode==='login'?'register':'login')}>Switch</button></div></div>); }
function Login({onSuccess}){ const [email,setEmail]=useState(''); const [pw,setPw]=useState(''); const submit=async(e)=>{ e.preventDefault(); const res=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:pw})}); if(res.ok){ const j=await res.json(); onSuccess(j.token); } else alert('login failed'); }; return (<form onSubmit={submit}><h3>Login</h3><input placeholder='email' value={email} onChange={e=>setEmail(e.target.value)}/><br/><input type='password' placeholder='password' value={pw} onChange={e=>setPw(e.target.value)}/><br/><button>Login</button></form>); }
function Register({onSuccess}){ const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [pw,setPw]=useState(''); const submit=async(e)=>{ e.preventDefault(); const res=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password:pw})}); if(res.ok){ const j=await res.json(); onSuccess(j.token); } else alert('register failed'); }; return (<form onSubmit={submit}><h3>Register</h3><input placeholder='Full name' value={name} onChange={e=>setName(e.target.value)}/><br/><input placeholder='email' value={email} onChange={e=>setEmail(e.target.value)}/><br/><input type='password' placeholder='password' value={pw} onChange={e=>setPw(e.target.value)}/><br/><button>Register</button></form>); }
function Calculator({token}){ const [gross,setGross]=useState(''); const [varp,setVar]=useState(''); const [nps,setNps]=useState(''); const [fy,setFy]=useState('2025-2026'); const [res,setRes]=useState(null); const submit=async(e)=>{ e.preventDefault(); const body={grossTotalPackage:Number(gross||0), variablePay:Number(varp||0), npsContribution:Number(nps||0), financialYearStr:fy}; const r=await fetch('/api/calculator/submit',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(body)}); if(r.ok){ setRes(await r.json()); } else { alert('calc failed'); } }; return (<div><form onSubmit={submit}><div><label>Gross:</label><input value={gross} onChange={e=>setGross(e.target.value)}/></div><div><label>Variable:</label><input value={varp} onChange={e=>setVar(e.target.value)}/></div><div><label>NPS:</label><input value={nps} onChange={e=>setNps(e.target.value)}/></div><div><label>FY:</label><select value={fy} onChange={e=>setFy(e.target.value)}><option>2024-2025</option><option>2025-2026</option><option>2026-2027</option></select></div><button>Calculate</button></form>{res && <pre>{JSON.stringify(res,null,2)}</pre>}</div>); }
