spring.datasource.url=jdbc:postgresql://localhost:5432/tax_calculator
spring.datasource.username=tax_user
spring.datasource.password=tax_pass
spring.jpa.hibernate.ddl-auto=update

frontend.origin=http://localhost:3000
server.port=8080
